#--------------------------------------------------------
# File: Makefile    Author(s): Author
# Date: 
#--------------------------------------------------------

DOCUMENT=doc
COMPILER=pdflatex

.PHONY: clean tex
tex:
	$(COMPILER) $(DOCUMENT).tex
clean:
	rm -f $(DOCUMENT).out $(DOCUMENT).log $(DOCUMENT).aux $(DOCUMENT).toc
